# Change these first
owner: exhive # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Exhive App
    url: https://exhive.app
  - name: Backend service
    url: https://prod-backend-service-780165197606.europe-west1.run.app/health
  - name: AI service
    url: https://prod-ai-service-780165197606.europe-west1.run.app
skipDeleteIssues: true
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: light
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/exhive/status/master/assets/favicon-48x48.svg
  favicon: https://raw.githubusercontent.com/exhive/status/master/assets/favicon-32x32.png
  css: |
    /* Hide the brand text that sits next to the logo */
    .navbar__title,
    .navbar__brand span {        /* Docusaurus v2 */
      display: none !important;
    }
    header .brand span {         /* Svelte-site template (Upptime ≥5) */
      display: none !important;
    }
  name: Exhive Status
  introTitle: "Exhive System Status Dashboard"
  introMessage: Live status monitoring for all Exhive services. Updated in real-time.
  navbar:
    - title: Overview
      href: /status
    - title: GitHub
      href: https://github.com/exhive/status
i18n:
  footer: Exhive Status © 2025
workflowSchedule:
  graphs: "0 0 * * *" # 00:00 UTC, once a day
  responseTime: "0 23 * * *" # 23:00 UTC, once a day
  staticSite: "0 1 * * *" # 01:00 UTC, once a day
  summary: "0 0 * * *" # 00:00 UTC, once a day
  updateTemplate: "0 0 * * *" # 00:00 UTC, once a day
  updates: "0 3 * * *" # 03:00 UTC, once a day
  uptime: "0 * * * *" # every hour on the hour
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

