# Change these first
owner: exhive # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Exhive App
    url: https://exhive.app
  - name: Backend service
    url: https://prod-backend-service-780165197606.europe-west1.run.app/health
  - name: AI service
    url: https://prod-ai-service-780165197606.europe-west1.run.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: light
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/exhive/status/master/assets/favicon-32x32.png
  favicon: https://raw.githubusercontent.com/exhive/status/master/assets/favicon-32x32.png
  name: Exhive Status
  introTitle: "Exhive System Status Dashboard"
  introMessage: Live status monitoring for all Exhive services. Updated in real-time.
  navbar:
    - title: Overview
      href: /status
    - title: GitHub
      href: https://github.com/exhive/status
i18n:
  footer: Exhive Status © 2025
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

